# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grahic_ui\mydialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class list_objs(object):
    def setupUi(self, MyDialog):
        MyDialog.setObjectName("MyDialog")
        MyDialog.resize(400, 400)
        #self.label = QtWidgets.QLabel(MyDialog)
        self.label = QtWidgets.QTextBrowser(MyDialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        #self.lineEdit_type = QtWidgets.QLineEdit(MyDialog)
        #self.lineEdit_type.setGeometry(QtCore.QRect(20, 40, 271, 200))
        #self.lineEdit_type.setObjectName("lineEdit_type")


        self.retranslateUi(MyDialog)
        QtCore.QMetaObject.connectSlotsByName(MyDialog)

    def retranslateUi(self, MyDialog):
        _translate = QtCore.QCoreApplication.translate
        MyDialog.setWindowTitle(_translate("MyDialog", "MyDialog"))
        #self.label.setText(_translate("MyDialog", "Список всех Объектов:"))

