# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grahic_ui\mydialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyDialog_cur_lev(object):
    def setupUi(self, MyDialog):
        MyDialog.setObjectName("MyDialog")
        MyDialog.resize(311, 183)
        self.label = QtWidgets.QLabel(MyDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_type = QtWidgets.QLineEdit(MyDialog)
        self.lineEdit_type.setGeometry(QtCore.QRect(20, 40, 271, 20))
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.pushButton_ok = QtWidgets.QPushButton(MyDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(20, 140, 121, 23))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(MyDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(154, 140, 131, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(MyDialog)
        QtCore.QMetaObject.connectSlotsByName(MyDialog)

    def retranslateUi(self, MyDialog):
        _translate = QtCore.QCoreApplication.translate
        MyDialog.setWindowTitle(_translate("MyDialog", "MyDialog"))
        self.label.setText(_translate("MyDialog", "Введите ID объекта:"))
        self.pushButton_ok.setText(_translate("MyDialog", "ОК"))
        self.pushButton_cancel.setText(_translate("MyDialog", "ОТМЕНА"))
